image: kmindi/android-ci:platforms-25-26-27

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  # Define cache-folders withing the build-folder to make it available for GitLab CI caching
  # http://stackoverflow.com/a/36050711/2170109
  # https://developer.android.com/studio/build/build-cache.html
  - grep -ciE 'processor' /proc/cpuinfo
  - export ANDROID_SDK_HOME=$CI_PROJECT_DIR
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  - echo 'y' | sdkmanager 'build-tools;28.0.3' 1> /dev/null

stages:
  - build
  - test
  - instrumentationtest
  - report

cache:
  key: "${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}"
  paths:
  - .gradle/
  - .android/build-cache/

build:tagged:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew assembleDebug
  artifacts:
    name: "SnmpCockpit_${CI_COMMIT_TAG}"
    paths:
    - app/build/outputs/apk/
  only:
    - tags
    
build:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew assembleDebug
  artifacts:
    name: "SnmpCockpit_${CI_JOB_ID}"
    expire_in: 1 week
    paths:
    - app/build/outputs/apk/
  except:
    - tags

test:unit:
  stage: test
  tags:
    - docker
  script:
    - ./gradlew test jacocoTestReport
    - cat "app/build/reports/jacoco/jacocoTestReport/html/index.html"
  coverage: '/Total.+?([0-9]{1,3})\%/'
  artifacts:
    name: "tests-unit-${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    expire_in: 6 h
    paths:
      - "app/build/intermediates/classes/debug"
      - "app/build/reports/*"
      - "app/build/jacoco/*.exec"

test:instrumentation:25:
  stage: instrumentationtest
  tags: 
    - docker
    - kvm
  script:
    - echo no | avdmanager -v create avd --force --name emulator-25 --abi google_apis/x86 --package "system-images;android-25;google_apis;x86"
    - export SHELL=/bin/bash && echo "no" | emulator -avd emulator-25 -noaudio -no-window -gpu off -skin 1080x1920 -verbose -qemu -enable-kvm &
    - adb wait-for-device
    - android-wait-for-emulator
    - adb shell settings put global window_animation_scale 0.0 &
    - adb shell settings put global transition_animation_scale 0.0 &
    - adb shell settings put global animator_duration_scale 0.0 &
    - export TERM=${TERM:-dumb}
    - export ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
    - assure_emulator_awake.sh "./gradlew createDebugCoverageReport" #createDebugCoverageReport calls connectedAndroidTests
    - cat "app/build/reports/coverage/debug/index.html"
  coverage: '/Total.+?([0-9]{1,3})\%/'
  allow_failure: true
  when: manual
  artifacts:
    name: "tests-instrumentation-25-${CI_JOB_NAME}"
    expire_in: 6 h
    paths:
      - "app/build/reports/*"
      - "app/build/outputs/code-coverage/connected/*.ec"

test:instrumentation:26_64:
  stage: instrumentationtest
  tags:
    - docker
    - kvm
  script:
    - echo no | avdmanager -v create avd --force --name emulator-26_64 --abi google_apis/x86_64 --package "system-images;android-26;google_apis;x86_64"
    - export SHELL=/bin/bash && echo "no" | emulator -avd emulator-26_64 -noaudio -no-window -gpu off -skin 1080x1920 -verbose -qemu -enable-kvm &
    - adb wait-for-device
    - android-wait-for-emulator
    - adb shell settings put global window_animation_scale 0.0 &
    - adb shell settings put global transition_animation_scale 0.0 &
    - adb shell settings put global animator_duration_scale 0.0 &
    - export TERM=${TERM:-dumb}
    - export ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
    - assure_emulator_awake.sh "./gradlew createDebugCoverageReport" #createDebugCoverageReport calls connectedAndroidTests
    - cat "app/build/reports/coverage/debug/index.html"
  coverage: '/Total.+?([0-9]{1,3})\%/'
  allow_failure: true
  when: manual
  artifacts:
    name: "tests-instrumentation-26_64-${CI_JOB_NAME}"
    expire_in: 6 h
    paths:
      - "app/build/reports/*"
      - "app/build/outputs/code-coverage/connected/*.ec"

test:instrumentation:26:
  stage: instrumentationtest
  tags:
    - docker
    - kvm
  script:
    - echo no | avdmanager -v create avd --force --name emulator-26 --abi google_apis/x86 --package "system-images;android-26;google_apis;x86"
    - export SHELL=/bin/bash && echo "no" | emulator -avd emulator-26 -noaudio -no-window -gpu off -skin 1080x1920 -verbose -qemu -enable-kvm &
    - adb wait-for-device
    - android-wait-for-emulator
    - adb shell settings put global window_animation_scale 0.0 &
    - adb shell settings put global transition_animation_scale 0.0 &
    - adb shell settings put global animator_duration_scale 0.0 &
    - export TERM=${TERM:-dumb}
    - export ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
    - assure_emulator_awake.sh "./gradlew createDebugCoverageReport" #createDebugCoverageReport calls connectedAndroidTests
    - cat "app/build/reports/coverage/debug/index.html"
  coverage: '/Total.+?([0-9]{1,3})\%/'
  allow_failure: true
  when: manual
  artifacts:
    name: "tests-instrumentation-26-${CI_JOB_NAME}"
    expire_in: 6 h
    paths:
      - "app/build/reports/*"
      - "app/build/outputs/code-coverage/connected/*.ec"


#test:instrumentation:27:
#  stage: instrumentationtest
#  tags:
#    - docker
#    - kvm
#  script:
#    - echo no | avdmanager -v create avd --force --name emulator-27 --abi google_apis/x86 --package "system-images;android-27;google_apis;x86"
#    - export SHELL=/bin/bash && echo "no" | emulator -avd emulator-27 -noaudio -no-window -gpu off -skin 1080x1920 -verbose -qemu -enable-kvm &
#    - adb wait-for-device
#    - android-wait-for-emulator
#    - adb shell settings put global window_animation_scale 0.0 &
#    - adb shell settings put global transition_animation_scale 0.0 &
#    - adb shell settings put global animator_duration_scale 0.0 &
#    - export TERM=${TERM:-dumb}
#    - export ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
#    - assure_emulator_awake.sh "./gradlew createDebugCoverageReport" #createDebugCoverageReport calls connectedAndroidTests
#    - cat "app/build/reports/coverage/debug/index.html"
#  coverage: '/Total.+?([0-9]{1,3})\%/'
#  allow_failure: true
#  when: manual
#  artifacts:
#    name: "tests-instrumentation-27-${CI_JOB_NAME}"
#    expire_in: 6 h
#    paths:
#      - "app/build/reports/*"
#      - "app/build/outputs/code-coverage/connected/*.ec"

reportAllCoverage:
  stage: report
  tags:
    - docker
  script:
    - ./gradlew jacocoTestReport
    - rm -dR "app/build/reports/coverage" || true
    - cat "app/build/reports/jacoco/jacocoTestReport/html/index.html"
  coverage: '/Total.+?([0-9]{1,3})\%/'
  artifacts:
    name: "build-reports-${CI_JOB_NAME}"
    expire_in: 1 week
    paths:
      - "app/build/reports/*"
  when: manual